import type { ReactNode } from 'react';
import { AlertTriangle, Clock, List, Rocket } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { SimpleHeader } from '../components/Shared';

export default function ConfirmacionDeInicio() {
  return <div className="screen"><SimpleHeader/><main style={{ display:'grid', placeItems:'center', paddingTop:230 }}><section className="card" style={{ width:1008, padding:'56px 60px', borderTop:'6px solid var(--brand)' }}><div style={{ textAlign:'center' }}><Rocket color="var(--brand)" size={64}/><h1 className="page-title" style={{ marginTop:32 }}>Confirmar Inicio</h1><p className="page-subtitle">Estás a punto de comenzar tu entrevista técnica. Por favor, revisa los detalles a continuación.</p></div><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, margin:'52px 0 48px' }}><Info icon={<Clock/>} label="Duración total" value="45 Minutos"/><Info icon={<List/>} label="Preguntas" value="5 Preguntas"/></div><div style={{ background:'var(--error-soft)', border:'1px solid #FF9E9E', color:'#9A0000', padding:28, display:'grid', gridTemplateColumns:'44px 1fr', gap:24, fontSize:22, lineHeight:1.35 }}><AlertTriangle/><div><b style={{ fontSize:18, letterSpacing:'.08em' }}>AVISO IMPORTANTE</b><p>Una vez que comiences el examen, el temporizador no se podrá pausar bajo ninguna circunstancia. Asegúrate de tener una conexión a internet estable y un ambiente libre de interrupciones.</p></div></div><hr style={{ margin:'60px 0 36px', border:'none', borderTop:'1px solid var(--border)' }}/><div style={{ display:'flex', justifyContent:'space-between' }}><Button variant="outline">Revisar requisitos</Button><Button>Comenzar examen</Button></div></section></main></div>;
}
function Info({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="card" style={{ background:'#FFF7FD', padding:28, display:'flex', gap:24, alignItems:'center' }}><span style={{ color:'var(--muted-2)' }}>{icon}</span><div><b style={{ letterSpacing:'.08em', textTransform:'uppercase', color:'var(--muted)' }}>{label}</b><div className="mono" style={{ marginTop:8, fontSize:22 }}>{value}</div></div></div>; }
