import type { ReactNode } from 'react';
import { ArrowRight, Mic, Video } from 'lucide-react';
import { TopBar } from '../components/Shared';
import { Button } from '../components/ui/Button';

export default function PruebaDeEquipo() {
  return <div className="screen"><TopBar/><main className="screen-inner" style={{ paddingTop:170 }}><div style={{ textAlign:'center', marginBottom:50 }}><h1 className="page-title" style={{ fontSize:48 }}>Asegúrate de que te ves y escuchas bien</h1><p className="page-subtitle">Calibración de equipo requerida antes de comenzar.</p></div><div style={{ display:'grid', gridTemplateColumns:'2fr 1fr', gap:24 }}><div className="video-frame" style={{ height:688, background:'radial-gradient(circle at 50% 24%, #e3d2c7 0 12%, transparent 13%), linear-gradient(90deg,#5f3b80,#222b3d 55%,#6d5b8b)' }}><div className="video-person" style={{ opacity:.95 }}/><div className="video-face" style={{ opacity:.95, background:'linear-gradient(#d6b09d,#8f6758)' }}/><div className="mono" style={{ position:'absolute', left:24, bottom:24, background:'#FFF7FD', border:'1px solid var(--border)', padding:'18px 36px', fontSize:20 }}>● CÁMARA EN<br/>VIVO</div></div><div style={{ display:'grid', gap:36 }}><section className="card" style={{ padding:28, height:188 }}><Device icon={<Video/>} label="CÁMARA"/><hr/><Device icon={<Mic/>} label="MICRÓFONO"/></section><section className="card" style={{ padding:24, display:'flex', flexDirection:'column', justifyContent:'center' }}><h3>CALIBRACIÓN DE AUDIO</h3><p className="page-subtitle">Habla en voz normal para probar los niveles.</p><div className="progress-line" style={{ height:46 }}><span style={{ width:'76%' }}/></div><div className="mono" style={{ display:'flex', justifyContent:'space-between', marginTop:16 }}><span>MIN</span><span style={{ color:'var(--success)' }}>IDEAL</span><span style={{ color:'var(--error)' }}>MAX</span></div></section></div></div><div style={{ textAlign:'center', marginTop:48 }}><Button>Comenzar entrevista <ArrowRight/></Button></div></main></div>;
}
function Device({ icon, label }: { icon: ReactNode; label: string }) { return <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', fontWeight:800, letterSpacing:'.08em' }}><span style={{ display:'flex', gap:18, alignItems:'center' }}>{icon}{label}</span><span className="badge success">● Conectado</span></div>; }
